---
- name: Install Jenkins
  hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  tasks:
     - debug: msg="This is test"
     - shell: "whoami"
       register: out 
     - debug: msg="{{out}}"
- name: verify master
  hosts: master
  gather_facts: true
  become: yes
  become_user: root
  tasks:
     - debug: msg="This is test"
     - shell: "whoami"
       register: out
     - debug: msg="{{out}}"
- name: verify node
  hosts: node
  gather_facts: true
  become: yes
  become_user: root
  tasks:
     - debug: msg="This is test"
     - shell: "whoami"
       register: out
     - debug: msg="{{out}}"
