---
# vars file for jenkinsAgent

slavename: TestSlave1
exec: 5
host: 172.16.3.103
port: 22
agentusername: aditiu
agentpassword: Add1426!
sshHostKeyVerificationStrategy: hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy
label: slave
userid: test@gmail.com
retrywait: 0
mode: NORMAL
remotefs: /home/aditiu/jenkins
retries: 0

masteruser: admin
masterpassword: admin
